package mybatis.mapper;

import java.util.List;
import mybatis.model.Department;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.department
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.department
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    int insert(Department row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.department
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    Department selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.department
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    List<Department> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.department
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    int updateByPrimaryKey(Department row);
}