package mybatis.mapper;

import java.util.List;
import mybatis.model.Employee;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    int insert(Employee row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    Employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    List<Employee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.employee
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    int updateByPrimaryKey(Employee row);
}