package mybatis.mapper;

import java.util.List;
import mybatis.model.Project;

public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.project
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.project
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    int insert(Project row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.project
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    Project selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.project
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    List<Project> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.project
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    int updateByPrimaryKey(Project row);
}