package mybatis.model;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.department.id
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.department.name
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.department.opt_lock_version
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    private Integer optLockVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.department.id
     *
     * @return the value of public.department.id
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.department.id
     *
     * @param id the value for public.department.id
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.department.name
     *
     * @return the value of public.department.name
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.department.name
     *
     * @param name the value for public.department.name
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.department.opt_lock_version
     *
     * @return the value of public.department.opt_lock_version
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public Integer getOptLockVersion() {
        return optLockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.department.opt_lock_version
     *
     * @param optLockVersion the value for public.department.opt_lock_version
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public void setOptLockVersion(Integer optLockVersion) {
        this.optLockVersion = optLockVersion;
    }
}