package mybatis.model;

import java.util.Date;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.id
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.first_name
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.last_name
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.opt_lock_version
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    private Integer optLockVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.insert_time
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.name
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.role
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.employee.department_id
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    private Integer departmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.id
     *
     * @return the value of public.employee.id
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.id
     *
     * @param id the value for public.employee.id
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.first_name
     *
     * @return the value of public.employee.first_name
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.first_name
     *
     * @param firstName the value for public.employee.first_name
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.last_name
     *
     * @return the value of public.employee.last_name
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.last_name
     *
     * @param lastName the value for public.employee.last_name
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.opt_lock_version
     *
     * @return the value of public.employee.opt_lock_version
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public Integer getOptLockVersion() {
        return optLockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.opt_lock_version
     *
     * @param optLockVersion the value for public.employee.opt_lock_version
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public void setOptLockVersion(Integer optLockVersion) {
        this.optLockVersion = optLockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.insert_time
     *
     * @return the value of public.employee.insert_time
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.insert_time
     *
     * @param insertTime the value for public.employee.insert_time
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.name
     *
     * @return the value of public.employee.name
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.name
     *
     * @param name the value for public.employee.name
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.role
     *
     * @return the value of public.employee.role
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.role
     *
     * @param role the value for public.employee.role
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.employee.department_id
     *
     * @return the value of public.employee.department_id
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.employee.department_id
     *
     * @param departmentId the value for public.employee.department_id
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }
}