package mybatis.model;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.project.id
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.project.description
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.project.title
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.project.opt_lock_version
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    private Integer optLockVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.project.id
     *
     * @return the value of public.project.id
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.project.id
     *
     * @param id the value for public.project.id
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.project.description
     *
     * @return the value of public.project.description
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.project.description
     *
     * @param description the value for public.project.description
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.project.title
     *
     * @return the value of public.project.title
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.project.title
     *
     * @param title the value for public.project.title
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.project.opt_lock_version
     *
     * @return the value of public.project.opt_lock_version
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public Integer getOptLockVersion() {
        return optLockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.project.opt_lock_version
     *
     * @param optLockVersion the value for public.project.opt_lock_version
     *
     * @mbg.generated Fri Mar 21 19:19:38 EET 2025
     */
    public void setOptLockVersion(Integer optLockVersion) {
        this.optLockVersion = optLockVersion;
    }
}